main: me.kasturez.elementalwar.Main
name: elementalwar
version: 1.0
author: kasturez
api-version: 1.16

commands:
  kits:
    usage: "/kits to open kits menu"
  guild:
    aliases:
      - g
  fly:
    usage: "you can fly"
  balance:
    aliases:
      - bal
      - money
      - cash
    usage: "do '/balance, /bal, /money, /cash' to open your balance"

